### ISSUE TITLE
Open page from url

### ISSUE THREAD

**Issue by jcubic** [kitze/sizzy#14]
It would be nice if you can get the sizzy url from real so you can share the link and open your site insidead of your home page. Maybe: http://sizzy.co/http://jcubic.pl or http://sizzy.co/?url=http://jcubic.pl

**Comment by kitze** [comment]
@jcubic the query param is ```initurl```, it just wasn't documented. I'm going to change it to ```url``` now and document it!

**Comment by jcubic** [comment]
Great, you can use history api to change the url while user type it so there is no need for documentation.
