### ISSUE TITLE
Iframes should have a default white background

### ISSUE THREAD

**Issue by johman10** [kitze/sizzy#16]
The browser normally parses white when there is no background color specified, since you specify a custom background color for the parent div, so pages that depend on having a white background look a lot more different.

I have an example right here: http://sizzy.co/?url=http%3A%2F%2Flucsengers.com

It seems like adding: `background-color: #FFFFFF` to every iframe should fix it (I would open a PR but seems like a very small fix).

**Comment by kitze** [comment]
Fixed! I was wondering why producthunt.com looks weird 😅
