### ISSUE TITLE
github does not show up

### ISSUE THREAD

**Issue by cprogrammer1994** [kitze/sizzy#18]
![image](https://cloud.githubusercontent.com/assets/11232402/25546498/a581a6be-2c63-11e7-86c5-39a54a0e26b8.png)

Noticed that github is not visible using sizzy. Is there a chance that github is blocking it?
Tested with some personal sites and those are working fine.

**Comment by yamboy1** [comment]
Google does the same thing

**Comment by kitze** [comment]
Hey @yamboy1, some of the websites prevent embedding into iframes. I'll find a solution for this soon!
