### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by JarnoVgr** [kitze/sizzy#22]
@kitze What do you prefer as license? Or is anything fine with you? :)
Thanks in advance.

**Comment by kitze** [comment]
@JarnoVgr I would like to add a license that says:
Anyone can use the code and mess with it locally, as long as they don't modify it and release it a separate website/extension/native app.

Can you help me figure out which license I need?

**Comment by Calinou** [comment]
I would suggest not going for that route, since that would not fit the [Open Source Definition](https://opensource.org/osd).

So, I'd advise you should go for a standard license like the [MIT license][https://choosealicense.com/licenses/mit/) instead.

**Comment by Kolyunya** [comment]
@kitze beware that `MIT` obviously does not suffice you intents. It would make legal for anyone to modify your code, release a separate app, close it's source or even release it under different license.

@Calinou why would you suggest anyone doing what he is not intended to do?

**Comment by hpvb** [comment]
You cannot get exactly the situation you want using any existing license. The definition of 'open source' or 'free software' does not allow for restrictions exactly like you seem to want. Placing restrictions on the code in that way also makes it difficult for your project to survive if you ever decide to stop working on it. 

A license such as that may also deter people from working together with you. Many people would consider such a restriction rather draconian. 

Judging by your description of what you want you may want to consider the GNU GPLv3. This will do the following:
* People will be able to fork/change your code and upload it but they cannot change the license.
* The license guarantees that every recipient of the software also gets a copy of the source code under the GPL license. This means that you will always be able to incorporate changes made by third parties into your own source tree.
* People cannot claim that the program was written by them, references to your work must remain.
* People not doing a public release of their fork will not have to do anything.

If your program can be run 'as a service' you could also consider the GNU Affero GPLv3. This will do the same as the 'normal' GPL but in addition adds the restriction that if users interact with the program over a network they also have a right to the source code. 

Depending on how your program works the resulting websites may also be under the GPL. If you want the output of your program to not be under such restrictions you can add an exception to the license of your program that explicitly places the output under a different license, perhaps the MIT license.

If you have any further questions please feel free to send me a private message.

**Comment by kitze** [comment]
Wow @hpvb thank you for the very detailed explanation. I have no experience with licensing open source projects, so sorry if my initial response in this thread looked overprotective. 

This helped me a lot with making the decision! Also thanks to @Kolyunya and @Calinou!

**Comment by hpvb** [comment]
You're welcome @kitze and thanks for your program. It looks very useful.
