### ISSUE TITLE
Finish light theme

### ISSUE THREAD

**Issue by kitze** [kitze/sizzy#3]

**Comment by SaraVieira** [comment]
Hello! 

Awesome project! Want help designing a white theme?

**Comment by kitze** [comment]
Hey @SaraVieira, thanks! Sure, you can give it a try!

The white theme is here -> https://github.com/kitze/sizzy/blob/master/src/styles/themes/light.js
But you need to also plug it in the themes object here ->  https://github.com/kitze/sizzy/blob/master/src/styles/themes.js

Let me know if you need anything else.

**Comment by SaraVieira** [comment]
@kitze Do you want to maintain the brown header or do I have freedom to change it ?

**Comment by SaraVieira** [comment]
@kitze Can I add eslint ? Maybe https://www.npmjs.com/package/eslint-config-airbnb ?

**Comment by kitze** [comment]
@SaraVieira you can change it, about eslint, the project already has a PR for using prettier, so there will be no need for eslint.

**Comment by SaraVieira** [comment]
@kitze How do you feel about this ?

<img width="1211" alt="screen shot 2017-04-30 at 14 24 53" src="https://cloud.githubusercontent.com/assets/1051509/25564687/d1cd76e6-2db0-11e7-9b4e-9ed09b16778b.png">

I was saying eslint because prettier doesn't give you syntax errors

**Comment by kitze** [comment]
@SaraVieira It's okay but needs more improvements:

-Header Is too ... bland
- Icons around "cog" and "orientation" over every device shouldn't have white borders
- Text color is too strong everywhere

**Comment by SaraVieira** [comment]
How about the colors like this ?

<img width="1209" alt="screen shot 2017-04-30 at 16 23 49" src="https://cloud.githubusercontent.com/assets/1051509/25565585/6d50326a-2dc1-11e7-849b-3a6377a0a4ac.png">

**Comment by kitze** [comment]
Looks better @SaraVieira !

Few more things I would change:

- Outline of icons in toolbar http://jmp.sh/hEe0svb
- The shadow under toolbar is too strong & url bar just looks ... wrong,  the outlines and the shadow should be way more subtle in the white theme http://jmp.sh/XtdSkmm 
- Maybe experiment with the header color? Keep it the same as in the purple theme or something?

**Comment by SaraVieira** [comment]
@kitze I changed the first two points to make it more subtle, I tried the purple border but I didn't really like it :/

<img width="1213" alt="screenshot 2017-04-30 20 07 48" src="https://cloud.githubusercontent.com/assets/1051509/25567208/b4321904-2de0-11e7-86e6-8362c904c174.png">

**Comment by kitze** [comment]
@SaraVieira I'm thinking that maybe I should remove the theming altogether, for now. It's hard to maintain 3 themes at once, especially with the changes that I have in mind. Also, I like the purple!

**Comment by SaraVieira** [comment]
@kitze duuude...

**Comment by SaraVieira** [comment]
@kitze Close this issue then ?

**Comment by kitze** [comment]
@SaraVieira I'll let it open for a while. If more people request a light theme we will finish it, otherwise, the dark theme will be also hidden.

Sorry if I caused any confusion but I'm still not sure in which direction the project is going :)

**Comment by SaraVieira** [comment]
@kitze No problem, I have it stashed in my computer, if you want it later let me know 👍
