### ISSUE TITLE
Toolbar URL input shows cropped text on Firefox

### ISSUE THREAD

**Issue by fvsch** [kitze/sizzy#32]
The `padding: 13px 36px 13px 13px` on the toolbar’s URL input only leaves 9px for the text, and Firefox happens to crop the text outside of this content area:

![screen shot 2017-04-30 at 13 09 14](https://cloud.githubusercontent.com/assets/243601/25563893/90fb11be-2da6-11e7-8629-fd728c84a231.png)

(Not a spec thing; probably related to how the Shadow DOM for this element is built.)

Using less top/bottom padding, e.g. with `padding: 4px 36px 4px 13px`, fixes the rendering:

![screen shot 2017-04-30 at 13 10 08](https://cloud.githubusercontent.com/assets/243601/25563901/b5b44b7e-2da6-11e7-8cc3-2278cc822d4f.png)

Browsers will center the input’s text vertically anyway, so the padding is not needed.

**Comment by kitze** [comment]
@fvsch thanks, fixed!
