### ISSUE TITLE
Restrict zoom to 5% increments

### ISSUE THREAD

**Issue by fvsch** [kitze/sizzy#46]
Rationale: hitting precise and useful zoom factors like `50%` gets hard with `1%` increments.

Downside: some users might find that a precise value such as `72%` is the sweet spot for fitting some configured boxes on their screen. That's a limited use case and they might find `70%` satisfactory as well.

Implementation using the step attribute:

```html
<input min="25" max="100" value="100" step="5" type="range">
```

**Comment by kitze** [comment]
@fvsch good point, but step="5" is not the solution I have in mind. I have some plans about refining zoom control which I'm going to implement soon. Thanks for your input!
