### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by kitze** [kitze/sizzy#5]
- [x] Design logo
- [ ] Add to header
- [ ] Add to GitHub readme
- [ ] Change favicon

**Comment by kandebonfim** [comment]
@mariogogh wanna help here?

**Comment by kitze** [comment]
@kandebonfim yes please, I already have something in mind but I'm not a logo designer. I would like something that includes rules/measurements/breakpoints, but it's also subtle and not so aggressive at the same time.

It would be good if you can help :)

**Comment by kandebonfim** [comment]
@kitze do you have some sketch I can start with? Or just the concept idea?

**Comment by kitze** [comment]
@kandebonfim I was thinking something like this ![img](https://pbs.twimg.com/profile_images/857925022505152512/huiuV-qi_400x400.jpg)  
but this won't work well in the header of the app :/

**Comment by SaraVieira** [comment]
<img width="508" alt="screen shot 2017-04-30 at 17 07 10" src="https://cloud.githubusercontent.com/assets/1051509/25565854/7c1b5008-2dc7-11e7-8a19-754415b1955a.png">

**Comment by kitze** [comment]
I love it @SaraVieira, thanks for the good job 🙌

I'm not sure about how it looks in the header though... Maybe some combination of the logo + the name, or the whole name in the logo for the header?

Anyway, adding it to the [Twitter account](https://twitter.com/sizzyapp) of Sizzy for now!

**Comment by SaraVieira** [comment]
Im gonna make some experiments and send you some screenshots 👍 

About this logo , I think it works great for github/twitter/electron app 😄

**Comment by SaraVieira** [comment]
<img width="943" alt="screenshot 2017-04-30 19 55 01" src="https://cloud.githubusercontent.com/assets/1051509/25567134/f3b0d072-2dde-11e7-8405-e554d84f9699.png">


What do you think ? @kitze

**Comment by kitze** [comment]
@SaraVieira Haha, the header looks too Christmas-y this way 😂 For now, I will use the logo on social media, blog posts, for the electron icon inc. 

Thank you!

**Comment by kitze** [comment]
@SaraVieira Ah, I need to use it as a favicon too!

**Comment by SaraVieira** [comment]
@kitze what about the website?  Maybe just add the lettering in that font then? 

I can do the switch of the readme and favicon if you want

**Comment by SaraVieira** [comment]
<img width="819" alt="screenshot 2017-04-30 21 03 04" src="https://cloud.githubusercontent.com/assets/1051509/25567560/70e946ec-2de8-11e7-9b44-bc6c7c83afac.png">

**Comment by SaraVieira** [comment]
<img width="225" alt="screenshot 2017-04-30 21 16 03" src="https://cloud.githubusercontent.com/assets/1051509/25567636/3ef17392-2dea-11e7-88e4-b4526f6f913a.png">

**Comment by SaraVieira** [comment]
![sizzly](https://cloud.githubusercontent.com/assets/1051509/25567652/9db87920-2dea-11e7-890d-353e6a64b024.png)

**Comment by glennreyes** [comment]
Great logo! ❤️

How would this look like in b/w?

**Comment by kitze** [comment]
@glennreyes what do you mean? How it would look with the black/white theme or how will a b/w variant of the logo look like?

**Comment by kitze** [comment]
@SaraVieira It's Sizzy not Sizzly 😅 Already added the favicon, maybe with few changes we can add the logo to the header:

http://jmp.sh/RF45cvQ
- Totally white color
- Align left position with first device
- More spacing between logo and url bar

**Comment by SaraVieira** [comment]
@kitze All fixed and you got yourself a PR 💃

**Comment by SaraVieira** [comment]
@kitze For posterioty reasons here is the Sizzy Branding:
https://www.dropbox.com/s/tgza8nmgtg84rhd/Sizzy.zip?dl=0

This includes:

1.  Sketch File
2. Header Logo
3. Main Logo

**Comment by SaraVieira** [comment]
@kitze Is there anything else I can help with ?

**Comment by kitze** [comment]
@SaraVieira nope, all good. Thank you very much!

**Comment by kandebonfim** [comment]
So happy to see your work, @SaraVieira! Nice result there...

**Comment by SaraVieira** [comment]
Thank you so much @kandebonfim
