### ISSUE TITLE
Set up a CI

### ISSUE THREAD

**Issue by mubaris** [kitze/sizzy#57]
This is an awesome tool. It would be better if we had CI.

**Comment by kitze** [comment]
Thank you @mubaris. Can you please elaborate about the CI?

**Comment by mubaris** [comment]
Continuous Integration tool is a build automation tool that help developers understand if their application is working by building, testing and reporting on the build sequences the developer has configured. 

So that you can test or build before you merge any PR. 

Cloud based CIs like [Travis CI](https://travis-ci.org) and [Circle CI](https://circleci.com) will be very useful for this. After you sign up in one of these, you can do the build testing. I honestly think #58 should be reopened and merged.

**Comment by kitze** [comment]
@mubaris I know what a CI is :) Sizzy is currently being built and deployed by Netlify, which also supports builds for separate branches.

You can read more about it here: https://www.netlify.com/docs/continuous-deployment/

**Comment by mubaris** [comment]
I didn't know you had CI. Cool :+1: . Closing now.
