### ISSUE TITLE
Provide share link

### ISSUE THREAD

**Issue by hwclass** [kitze/sizzy#62]
Hi all,

During playing with Sizzy, noticed that providing a share link for the app/site being tested. I know, I think Sizzy will need a server-side rendered page but it would be really useful to catch and follow the stuff among teams and so on.

Thanks

Baris

**Comment by kitze** [comment]
Hey @hwclass , can you please explain more? I'm not sure I can understand what you're saying. I'll be glad to help 👍

**Comment by kitze** [comment]
@hwclass You can already share a link by appending ?url=link to the end of the url.
Example:

http://sizzy.co/?url=http://kitze.io

I'm not sure if you're asking about this or something else.

**Comment by hwclass** [comment]
Hi @kitze 

Yes, that's what I mean. I have just also tried to share in some social media applications and they can generate the screenshot from the the link.

Closing the issue.

Thanks...
