### ISSUE TITLE
Sizzy install fails with npm and yarn

### ISSUE THREAD

**Issue by dlewand691** [kitze/sizzy#81]
So trying to update to the latest and getting the errors "No valid versions found for \"sizzy\". The package may be unpublished." and "Couldn't find package \"Sizzy\" on the \"npm\" registry.". 

Is Sizzy dead? Sure hope not!

**Comment by dlewand691** [comment]
Well, when trying to install with yarn I get this error:

yarn add v1.5.1
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "No valid versions found for \"sizzy\". The package may be unpublished.".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ctsuser1/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Was using it locally and wanted to update.

**Comment by dlewand691** [comment]
Still can't install locally. With Yarn, getting this error:

```
➜  ~ sudo yarn add sizzy
yarn add v1.5.1
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "No valid versions found for \"sizzy\". The package may be unpublished.".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ctsuser1/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
➜  ~ sudo yarn add sizzy
yarn add v1.5.1
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "No valid versions found for \"sizzy\". The package may be unpublished.".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ctsuser1/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
➜  ~ 
```

With NPM getting this error:

```
➜  ~ sudo npm install sizzy
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for sizzy

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ctsuser1/.npm/_logs/2018-04-30T18_48_16_648Z-debug.log
➜  ~ 
```

Any thoughts?

**Comment by SaraVieira** [comment]
It's not on npm

**Comment by dlewand691** [comment]
Major brain fart moment. Realized in the shower this morning I was treating it as a plugin. I'm an idiot, sorry. Working perfect now!
